services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: larry_battery_backend
      POSTGRES_PASSWORD: larry_battery_backend
      POSTGRES_DB: larry_battery_backend
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data